// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebMonitoreoWhatsapp.Models;

namespace WebApiMonitoreo.Migrations
{
    [DbContext(typeof(ApplicationDbContextOne))]
    [Migration("20180406044131_changenamesTabless")]
    partial class changenamesTabless
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("WebMonitoreoWhatsapp.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("grupos");
                });

            modelBuilder.Entity("WebMonitoreoWhatsapp.Models.GrupoUsuario", b =>
                {
                    b.Property<int>("GrupoId");

                    b.Property<int>("UsuarioId");

                    b.HasKey("GrupoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("grupousuarios");
                });

            modelBuilder.Entity("WebMonitoreoWhatsapp.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<int>("GrupoId");

                    b.Property<string>("Tipo");

                    b.Property<int>("UsuarioID");

                    b.Property<DateTime>("fecha");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("UsuarioID");

                    b.ToTable("mensajes");
                });

            modelBuilder.Entity("WebMonitoreoWhatsapp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("WebMonitoreoWhatsapp.Models.GrupoUsuario", b =>
                {
                    b.HasOne("WebMonitoreoWhatsapp.Models.Grupo", "Grupo")
                        .WithMany("GruposUsuarios")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebMonitoreoWhatsapp.Models.Usuario", "Usuario")
                        .WithMany("GruposUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebMonitoreoWhatsapp.Models.Mensaje", b =>
                {
                    b.HasOne("WebMonitoreoWhatsapp.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebMonitoreoWhatsapp.Models.Usuario", "Usuario")
                        .WithMany("mensajes")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
